### ISSUE TITLE
VlanInterface.Mtu field has bogus tag format

### ISSUE THREAD

**Issue by maksym-nazarenko** [ddelnano/terraform-provider-mikrotik#125]
The [Mtu field](https://github.com/ddelnano/terraform-provider-mikrotik/blob/006ea157d77bb7d1fd3678a7f9b9321ea8517b33/client/vlan_interface.go#L12) has invalid format, so it cannot be used as `reflect.StructTag`

```go
type VlanInterface struct {
	Id            string `mikrotik:".id"`
	Interface     string `mikrotik:"interface"`
	Mtu           int    `mikrotik:"mtu` <-- no closing quote
	...
}
```

**TODO**
- [x] Add test to reveal the issue
- [x] Fix syntax of the tag
- [x] ~Create another issue to introduce linter to the project (`go vet` as the first step 🤔 ?)~ New target/step in Makefile/Github actions added
