### ISSUE TITLE
Migrate all resources from SDKv2 to new PluginFramework

### ISSUE THREAD

**Issue by maksym-nazarenko** [ddelnano/terraform-provider-mikrotik#145]
List of resources (create PR and tick the box):
- [x] mikrotik_bgp_instance (#188)
- [x] mikrotik_bgp_peer (#180)
- [x] mikrotik_bridge (#191)
- [x] mikrotik_bridge_port (#192)
- [x] mikrotik_bridge_vlan (#193)
- [x] mikrotik_dhcp_lease (#186)
- [x] mikrotik_dhcp_server (#195)
- [x] mikrotik_dhcp_server_network (#196)
- [x] mikrotik_dns_record (#198)
- [x] mikrotik_firewall_filter_rule (#202)
- [x] mikrotik_interface_list (#199)
- [x] mikrotik_interface_list_member (#200)
- [x] mikrotik_ip_address (#201)
- [x] mikrotik_ipv6_address (#185)
- [x] mikrotik_pool (#184)
- [x] mikrotik_script (#177)
- [x] mikrotik_vlan_interface (#187)

Example implementations:
- [mikrotik_scheduler](https://github.com/ddelnano/terraform-provider-mikrotik/blob/master/mikrotik/resource_scheduler.go) resource

### Generate files using `codegen` tool
1. Add proper [struct tags](https://github.com/ddelnano/terraform-provider-mikrotik/tree/master/cmd/mikrotik-codegen/internal/codegen#terraform-resource) to the MikroTik client resource and run
    ```shell
    $ go run cmd/mikrotik-codegen/main.go terraform -src client/script.go Script
    ```

2. Check the code for possible syntax errors and adjust tests (if necessary).

### Pitfalls and known issues

**Tests which use `Primary.ID` field of the state**
It is caused by transition to proper usage of `Primary.ID` Terraform state field, when it is always equals to MikroTik's `.id` rather then `name` or something else. To fix this, check the test file and replace occurrence with `Primary.Attributes["proper attribute"]`.

**Import tests**
Usually caused by usage the resource's `ID` for importing by default. To change it to any other value, just use `ImportStateId` field in `TestStep`.

**Provider does not support mikrotik_XXX resource**
If resource uses `Default` value for its attribute, this attribute must be `Computed`

**Comment by maksym-nazarenko** [comment]
finally, this issue is closed 🎉
